In [2]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [11]:
print("data type of list is: ",type(list_))       
print("data type of array_list is: ",type(array_list))

data type of list is:  <class 'list'>
data type of array_list is:  <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [5]:
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)
for element in list_:
    print(type(element))


for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#Consider the below code to answer further questions:

        import numpy as np
        num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
        num_array = np.array(object = num_list)
    #Q4. Write a code to find the following characteristics of variable, num_array:
    #(i)	 shape
    #(ii)    size


In [10]:
num_shape=num_array.shape
print("num_array shape is: ",num_shape)
num_size=num_array.size
print("num_array size is: ",num_size)

num_array shape is:  (2, 3)
num_array size is:  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

        [Hint: The size of the array will be 9 and the shape will be (3,3).]


In [12]:
import numpy as np
zeros_array = np.zeros(shape=(3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
        [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
identity_array = np.identity(n=5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
